import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/global.scss";
import CenteredContainer from "@/components/layout/CenteredContainer/CenteredContainer";
import Card from "@/components/ui/Card/Card";
import Header from "@/components/shared/Header/Header";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SiaExplains.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link key="GoogleFontsPreConnect" rel="preconnect" href="https://fonts.googleapis.com" />
        <link key="GoogleFontsGStaticConnect" rel="preconnect" href="https://fonts.gstatic.com" />
        <link key="GoogleFontsHref" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

      <CenteredContainer>
        <Card bottomLessRadius={true}>
         <Header />
        </Card>
        {children}
        </CenteredContainer>
      </body>
    </html>
  );
}
