import type { ComponentType } from "react";
import {
  AlarmClock, Archive, AtSign, Award, Baby, Bell, Bike, Blocks, Book, Bookmark, BookOpen, Bot, Boxes, Brain, Briefcase,
  Brush, Bug, Building2, Calculator, Calendar, CalendarDays, Camera, Car, ChartBar, ChartLine, ChartPie,
  CircleQuestionMark, Clapperboard, Clock, Cloud, CloudSun, Code, Coffee, Coins, Compass, Contact, Cpu, CreditCard,
  Crown, Database, DollarSign, Download, Dumbbell, Euro, ExternalLink, Eye, FileCode, FileText, Film, Flag, Flame,
  Folder, Gamepad2, Gift, GitBranch, Globe, GraduationCap, Hammer, HandHeart, Handshake, Headphones, Heart,
  HeartHandshake, Hourglass, House, IdCard, Image, Inbox, Info, Key, Keyboard, Landmark, Languages, Laptop, Layers,
  Leaf, Library, Lightbulb, Link, Link2, Lock, Mail, Map, MapPin, Medal, Megaphone, MessageCircle, MessageSquare,
  Mic, Monitor, Moon, Mountain, Music, Newspaper, NotebookPen, Package, Palette, PawPrint, PenLine, Phone, PiggyBank,
  Pin, Pizza, Plane, Podcast, Printer, Puzzle, QrCode, Radio, Receipt, Rocket, Rss, School, ScrollText, Search, Send,
  Server, Settings, Share2, Shield, ShieldCheck, Shirt, ShoppingBag, ShoppingCart, Smartphone, Smile, Sparkles, Star,
  Store, Sun, Tag, Target, Terminal, ThumbsUp, Ticket, Timer, TrainFront, TreePine, TrendingUp, Trophy, Tv, Upload,
  UserPlus, UserRound, Users, UsersRound, Utensils, Video, Wallet, Wifi, Wrench, Zap,
} from "lucide-react";
import {
  siAirbnb, siAnthropic, siApple, siApplepodcasts, siAppstore, siBehance, siBitbucket, siBluesky, siBuymeacoffee,
  siCalendly, siClaude, siCoursera, siDevdotto, siDiscord, siDribbble, siEtsy, siFacebook, siFigma, siFiverr,
  siGitlab, siGlassdoor, siGoodreads, siGooglemaps, siGooglemeet, siGoogleplay, siGumroad, siHashnode, siHuggingface,
  siIndeed, siItchdotio, siKaggle, siKick, siKofi, siLeetcode, siLetterboxd, siLine, siLinktree, siMastodon,
  siMedium, siMessenger, siNotion, siNpm, siPatreon, siPaypal, siPinterest, siPlaystation, siProducthunt, siQuora,
  siReddit, siSignal, siSnapchat, siSoundcloud, siSpotify, siStackoverflow, siSteam, siStrava, siStripe, siSubstack,
  siTelegram, siThreads, siTiktok, siTripadvisor, siTumblr, siTwitch, siUdemy, siUpwork, siViber, siVimeo, siVk,
  siWechat, siWellfound, siWhatsapp, siWikipedia, siXing, siYoutubemusic, siZoom, type BrandIconData,
} from "@/lib/brand-icons.generated";
import { GithubIcon, InstagramIcon, LinkedinIcon, TwitterIcon, YoutubeIcon } from "@/components/SocialIcons";

export type IconComponent = ComponentType<{ size?: number; className?: string }>;

export const ICON_GROUPS = [
  "Social & media",
  "Communication",
  "People & community",
  "Work & dev",
  "Learning & content",
  "Money & shopping",
  "Time & events",
  "Places & life",
  "General",
] as const;

export type IconGroup = (typeof ICON_GROUPS)[number];

type IconDef = { label: string; Icon: IconComponent; group: IconGroup; keywords: string; color?: string };

/** A Simple Icons logo (CC0) in the same props shape as the lucide icons, plus its brand colour. */
function brand(icon: BrandIconData): { Icon: IconComponent; color: string } {
  function BrandIcon({ size = 24, className }: { size?: number; className?: string }) {
    return (
      <svg role="img" aria-hidden width={size} height={size} viewBox="0 0 24 24" fill="currentColor" className={className}>
        <path d={icon.path} />
      </svg>
    );
  }
  BrandIcon.displayName = `${icon.title}Icon`;
  return { Icon: BrandIcon, color: `#${icon.hex}` };
}

/**
 * Every icon a link can use. Keys are what's stored in `links.icon`, so never rename one —
 * add a new key instead. Unknown stored values fall back to "link".
 */
export const LINK_ICON_REGISTRY = {
  // Social & media
  youtube: { label: "YouTube", Icon: YoutubeIcon, group: "Social & media", keywords: "video channel" },
  instagram: { label: "Instagram", Icon: InstagramIcon, group: "Social & media", keywords: "photo reels" },
  github: { label: "GitHub", Icon: GithubIcon, group: "Social & media", keywords: "code repo git" },
  linkedin: { label: "LinkedIn", Icon: LinkedinIcon, group: "Social & media", keywords: "job career" },
  x: { label: "X / Twitter", Icon: TwitterIcon, group: "Social & media", keywords: "twitter tweet" },

  // Brand logos from Simple Icons, filed under the group they belong to
  telegram: { label: "Telegram", group: "Communication", keywords: "messenger chat channel group", ...brand(siTelegram) },
  whatsapp: { label: "WhatsApp", group: "Communication", keywords: "messenger chat", ...brand(siWhatsapp) },
  signal: { label: "Signal", group: "Communication", keywords: "messenger private chat", ...brand(siSignal) },
  messenger: { label: "Messenger", group: "Communication", keywords: "facebook chat", ...brand(siMessenger) },
  discord: { label: "Discord", group: "Communication", keywords: "server community chat gaming", ...brand(siDiscord) },
  wechat: { label: "WeChat", group: "Communication", keywords: "messenger china", ...brand(siWechat) },
  line: { label: "LINE", group: "Communication", keywords: "messenger chat", ...brand(siLine) },
  viber: { label: "Viber", group: "Communication", keywords: "messenger call", ...brand(siViber) },
  zoom: { label: "Zoom", group: "Communication", keywords: "video call meeting", ...brand(siZoom) },
  "google-meet": { label: "Google Meet", group: "Communication", keywords: "video call meeting", ...brand(siGooglemeet) },
  calendly: { label: "Calendly", group: "Time & events", keywords: "booking schedule meeting", ...brand(siCalendly) },
  facebook: { label: "Facebook", group: "Social & media", keywords: "meta social", ...brand(siFacebook) },
  threads: { label: "Threads", group: "Social & media", keywords: "meta instagram social", ...brand(siThreads) },
  bluesky: { label: "Bluesky", group: "Social & media", keywords: "social bsky", ...brand(siBluesky) },
  mastodon: { label: "Mastodon", group: "Social & media", keywords: "fediverse social", ...brand(siMastodon) },
  reddit: { label: "Reddit", group: "Social & media", keywords: "forum community subreddit", ...brand(siReddit) },
  tiktok: { label: "TikTok", group: "Social & media", keywords: "short video reels", ...brand(siTiktok) },
  snapchat: { label: "Snapchat", group: "Social & media", keywords: "stories", ...brand(siSnapchat) },
  pinterest: { label: "Pinterest", group: "Social & media", keywords: "pins boards", ...brand(siPinterest) },
  tumblr: { label: "Tumblr", group: "Social & media", keywords: "blog", ...brand(siTumblr) },
  vk: { label: "VK", group: "Social & media", keywords: "vkontakte social", ...brand(siVk) },
  quora: { label: "Quora", group: "Social & media", keywords: "questions answers", ...brand(siQuora) },
  xing: { label: "XING", group: "Social & media", keywords: "career job germany", ...brand(siXing) },
  twitch: { label: "Twitch", group: "Social & media", keywords: "stream live gaming", ...brand(siTwitch) },
  kick: { label: "Kick", group: "Social & media", keywords: "stream live", ...brand(siKick) },
  vimeo: { label: "Vimeo", group: "Social & media", keywords: "video", ...brand(siVimeo) },
  spotify: { label: "Spotify", group: "Social & media", keywords: "music podcast playlist", ...brand(siSpotify) },
  "apple-podcasts": { label: "Apple Podcasts", group: "Social & media", keywords: "podcast audio", ...brand(siApplepodcasts) },
  "youtube-music": { label: "YouTube Music", group: "Social & media", keywords: "music songs", ...brand(siYoutubemusic) },
  soundcloud: { label: "SoundCloud", group: "Social & media", keywords: "music audio", ...brand(siSoundcloud) },
  linktree: { label: "Linktree", group: "Social & media", keywords: "link in bio", ...brand(siLinktree) },
  medium: { label: "Medium", group: "Learning & content", keywords: "blog articles writing", ...brand(siMedium) },
  substack: { label: "Substack", group: "Learning & content", keywords: "newsletter blog writing", ...brand(siSubstack) },
  "dev-to": { label: "DEV", group: "Learning & content", keywords: "dev.to blog articles", ...brand(siDevdotto) },
  hashnode: { label: "Hashnode", group: "Learning & content", keywords: "blog dev", ...brand(siHashnode) },
  wikipedia: { label: "Wikipedia", group: "Learning & content", keywords: "wiki encyclopedia", ...brand(siWikipedia) },
  udemy: { label: "Udemy", group: "Learning & content", keywords: "course learn", ...brand(siUdemy) },
  coursera: { label: "Coursera", group: "Learning & content", keywords: "course learn university", ...brand(siCoursera) },
  goodreads: { label: "Goodreads", group: "Learning & content", keywords: "books reading", ...brand(siGoodreads) },
  letterboxd: { label: "Letterboxd", group: "Learning & content", keywords: "movies films reviews", ...brand(siLetterboxd) },
  notion: { label: "Notion", group: "Work & dev", keywords: "notes docs wiki", ...brand(siNotion) },
  gitlab: { label: "GitLab", group: "Work & dev", keywords: "git repo code", ...brand(siGitlab) },
  bitbucket: { label: "Bitbucket", group: "Work & dev", keywords: "git repo code", ...brand(siBitbucket) },
  npm: { label: "npm", group: "Work & dev", keywords: "package javascript", ...brand(siNpm) },
  "stack-overflow": { label: "Stack Overflow", group: "Work & dev", keywords: "questions code answers", ...brand(siStackoverflow) },
  leetcode: { label: "LeetCode", group: "Work & dev", keywords: "coding interview", ...brand(siLeetcode) },
  kaggle: { label: "Kaggle", group: "Work & dev", keywords: "data science ml", ...brand(siKaggle) },
  "hugging-face": { label: "Hugging Face", group: "Work & dev", keywords: "ai ml models", ...brand(siHuggingface) },
  claude: { label: "Claude", group: "Work & dev", keywords: "ai anthropic assistant", ...brand(siClaude) },
  anthropic: { label: "Anthropic", group: "Work & dev", keywords: "ai claude", ...brand(siAnthropic) },
  figma: { label: "Figma", group: "Work & dev", keywords: "design ui", ...brand(siFigma) },
  dribbble: { label: "Dribbble", group: "Work & dev", keywords: "design portfolio", ...brand(siDribbble) },
  behance: { label: "Behance", group: "Work & dev", keywords: "design portfolio", ...brand(siBehance) },
  "product-hunt": { label: "Product Hunt", group: "Work & dev", keywords: "launch startup", ...brand(siProducthunt) },
  wellfound: { label: "Wellfound", group: "Work & dev", keywords: "angellist startup jobs", ...brand(siWellfound) },
  upwork: { label: "Upwork", group: "Work & dev", keywords: "freelance hire", ...brand(siUpwork) },
  fiverr: { label: "Fiverr", group: "Work & dev", keywords: "freelance gigs", ...brand(siFiverr) },
  indeed: { label: "Indeed", group: "Work & dev", keywords: "jobs career", ...brand(siIndeed) },
  glassdoor: { label: "Glassdoor", group: "Work & dev", keywords: "jobs reviews salary", ...brand(siGlassdoor) },
  patreon: { label: "Patreon", group: "Money & shopping", keywords: "support membership creator", ...brand(siPatreon) },
  "ko-fi": { label: "Ko-fi", group: "Money & shopping", keywords: "tip donate coffee support", ...brand(siKofi) },
  "buy-me-a-coffee": { label: "Buy Me a Coffee", group: "Money & shopping", keywords: "tip donate support", ...brand(siBuymeacoffee) },
  paypal: { label: "PayPal", group: "Money & shopping", keywords: "pay donate money", ...brand(siPaypal) },
  stripe: { label: "Stripe", group: "Money & shopping", keywords: "pay checkout", ...brand(siStripe) },
  gumroad: { label: "Gumroad", group: "Money & shopping", keywords: "sell digital products", ...brand(siGumroad) },
  etsy: { label: "Etsy", group: "Money & shopping", keywords: "shop handmade", ...brand(siEtsy) },
  apple: { label: "Apple", group: "Money & shopping", keywords: "mac iphone", ...brand(siApple) },
  "app-store": { label: "App Store", group: "Money & shopping", keywords: "ios app download", ...brand(siAppstore) },
  "google-play": { label: "Google Play", group: "Money & shopping", keywords: "android app download", ...brand(siGoogleplay) },
  steam: { label: "Steam", group: "Social & media", keywords: "games gaming", ...brand(siSteam) },
  playstation: { label: "PlayStation", group: "Social & media", keywords: "games gaming psn", ...brand(siPlaystation) },
  "itch-io": { label: "itch.io", group: "Social & media", keywords: "indie games", ...brand(siItchdotio) },
  strava: { label: "Strava", group: "Places & life", keywords: "running cycling sport", ...brand(siStrava) },
  airbnb: { label: "Airbnb", group: "Places & life", keywords: "travel stay rent", ...brand(siAirbnb) },
  tripadvisor: { label: "Tripadvisor", group: "Places & life", keywords: "travel reviews", ...brand(siTripadvisor) },
  "google-maps": { label: "Google Maps", group: "Places & life", keywords: "map location directions", ...brand(siGooglemaps) },

  // Social & media (generic)
  video: { label: "Video", Icon: Video, group: "Social & media", keywords: "camera stream" },
  podcast: { label: "Podcast", Icon: Podcast, group: "Social & media", keywords: "audio show" },
  radio: { label: "Radio", Icon: Radio, group: "Social & media", keywords: "broadcast live" },
  tv: { label: "TV", Icon: Tv, group: "Social & media", keywords: "television stream" },
  film: { label: "Film", Icon: Film, group: "Social & media", keywords: "movie cinema" },
  clapperboard: { label: "Clapperboard", Icon: Clapperboard, group: "Social & media", keywords: "movie production" },
  camera: { label: "Camera", Icon: Camera, group: "Social & media", keywords: "photo photography" },
  image: { label: "Image", Icon: Image, group: "Social & media", keywords: "photo picture gallery" },
  music: { label: "Music", Icon: Music, group: "Social & media", keywords: "song spotify playlist tiktok" },
  headphones: { label: "Headphones", Icon: Headphones, group: "Social & media", keywords: "audio listen" },
  mic: { label: "Microphone", Icon: Mic, group: "Social & media", keywords: "voice record talk" },
  rss: { label: "RSS", Icon: Rss, group: "Social & media", keywords: "feed subscribe" },
  gamepad: { label: "Gaming", Icon: Gamepad2, group: "Social & media", keywords: "game twitch discord play" },

  // Communication
  mail: { label: "Email", Icon: Mail, group: "Communication", keywords: "email newsletter contact" },
  send: { label: "Send", Icon: Send, group: "Communication", keywords: "telegram message" },
  "message-circle": { label: "Chat bubble", Icon: MessageCircle, group: "Communication", keywords: "whatsapp chat dm" },
  "message-square": { label: "Message", Icon: MessageSquare, group: "Communication", keywords: "chat comment discord" },
  phone: { label: "Phone", Icon: Phone, group: "Communication", keywords: "call" },
  smartphone: { label: "Smartphone", Icon: Smartphone, group: "Communication", keywords: "mobile app ios android" },
  "at-sign": { label: "At sign", Icon: AtSign, group: "Communication", keywords: "handle mention threads" },
  bell: { label: "Bell", Icon: Bell, group: "Communication", keywords: "notification alert subscribe" },
  megaphone: { label: "Megaphone", Icon: Megaphone, group: "Communication", keywords: "announce marketing" },
  inbox: { label: "Inbox", Icon: Inbox, group: "Communication", keywords: "mail messages" },
  contact: { label: "Contact card", Icon: Contact, group: "Communication", keywords: "vcard address book" },
  languages: { label: "Languages", Icon: Languages, group: "Communication", keywords: "translate i18n" },

  // People & community
  users: { label: "Users", Icon: Users, group: "People & community", keywords: "community group team" },
  "users-round": { label: "Group", Icon: UsersRound, group: "People & community", keywords: "community team people" },
  user: { label: "Person", Icon: UserRound, group: "People & community", keywords: "profile me about" },
  "user-plus": { label: "Join", Icon: UserPlus, group: "People & community", keywords: "signup follow invite" },
  handshake: { label: "Handshake", Icon: Handshake, group: "People & community", keywords: "partner deal agreement" },
  "heart-handshake": { label: "Support", Icon: HeartHandshake, group: "People & community", keywords: "charity nonprofit volunteer" },
  "hand-heart": { label: "Donate", Icon: HandHeart, group: "People & community", keywords: "charity give support" },
  heart: { label: "Heart", Icon: Heart, group: "People & community", keywords: "love like favorite" },
  smile: { label: "Smile", Icon: Smile, group: "People & community", keywords: "happy fun" },
  baby: { label: "Baby", Icon: Baby, group: "People & community", keywords: "kids family" },
  "paw-print": { label: "Pets", Icon: PawPrint, group: "People & community", keywords: "dog cat animal" },
  "id-card": { label: "ID card", Icon: IdCard, group: "People & community", keywords: "badge identity cv resume" },

  // Work & dev
  code: { label: "Code", Icon: Code, group: "Work & dev", keywords: "programming developer" },
  terminal: { label: "Terminal", Icon: Terminal, group: "Work & dev", keywords: "cli shell command" },
  "file-code": { label: "Code file", Icon: FileCode, group: "Work & dev", keywords: "source script" },
  "git-branch": { label: "Git branch", Icon: GitBranch, group: "Work & dev", keywords: "version control gitlab" },
  bug: { label: "Bug", Icon: Bug, group: "Work & dev", keywords: "issue debug" },
  server: { label: "Server", Icon: Server, group: "Work & dev", keywords: "hosting backend" },
  database: { label: "Database", Icon: Database, group: "Work & dev", keywords: "data sql storage" },
  cloud: { label: "Cloud", Icon: Cloud, group: "Work & dev", keywords: "hosting aws saas" },
  cpu: { label: "CPU", Icon: Cpu, group: "Work & dev", keywords: "chip hardware tech" },
  bot: { label: "Bot", Icon: Bot, group: "Work & dev", keywords: "ai robot assistant chatbot" },
  brain: { label: "Brain", Icon: Brain, group: "Work & dev", keywords: "ai mind think" },
  sparkles: { label: "Sparkles", Icon: Sparkles, group: "Work & dev", keywords: "ai magic new" },
  rocket: { label: "Rocket", Icon: Rocket, group: "Work & dev", keywords: "launch startup ship" },
  wrench: { label: "Wrench", Icon: Wrench, group: "Work & dev", keywords: "tools fix" },
  hammer: { label: "Hammer", Icon: Hammer, group: "Work & dev", keywords: "build tools" },
  settings: { label: "Settings", Icon: Settings, group: "Work & dev", keywords: "gear config" },
  puzzle: { label: "Puzzle", Icon: Puzzle, group: "Work & dev", keywords: "plugin extension" },
  layers: { label: "Layers", Icon: Layers, group: "Work & dev", keywords: "stack design" },
  boxes: { label: "Boxes", Icon: Boxes, group: "Work & dev", keywords: "products modules" },
  package: { label: "Package", Icon: Package, group: "Work & dev", keywords: "npm product box" },
  blocks: { label: "Blocks", Icon: Blocks, group: "Work & dev", keywords: "apps components" },
  briefcase: { label: "Briefcase", Icon: Briefcase, group: "Work & dev", keywords: "job work business portfolio" },
  building: { label: "Company", Icon: Building2, group: "Work & dev", keywords: "office business startup" },
  laptop: { label: "Laptop", Icon: Laptop, group: "Work & dev", keywords: "computer work remote" },
  monitor: { label: "Monitor", Icon: Monitor, group: "Work & dev", keywords: "desktop screen website" },
  keyboard: { label: "Keyboard", Icon: Keyboard, group: "Work & dev", keywords: "typing" },
  printer: { label: "Printer", Icon: Printer, group: "Work & dev", keywords: "print" },
  palette: { label: "Palette", Icon: Palette, group: "Work & dev", keywords: "design art color dribbble behance" },
  brush: { label: "Brush", Icon: Brush, group: "Work & dev", keywords: "paint art design editor" },
  "pen-line": { label: "Pen", Icon: PenLine, group: "Work & dev", keywords: "write edit sign" },
  "chart-bar": { label: "Bar chart", Icon: ChartBar, group: "Work & dev", keywords: "analytics stats" },
  "chart-line": { label: "Line chart", Icon: ChartLine, group: "Work & dev", keywords: "analytics growth" },
  "chart-pie": { label: "Pie chart", Icon: ChartPie, group: "Work & dev", keywords: "analytics report" },
  "trending-up": { label: "Trending up", Icon: TrendingUp, group: "Work & dev", keywords: "growth stocks" },
  target: { label: "Target", Icon: Target, group: "Work & dev", keywords: "goal focus aim" },
  shield: { label: "Shield", Icon: Shield, group: "Work & dev", keywords: "security protect" },
  "shield-check": { label: "Verified", Icon: ShieldCheck, group: "Work & dev", keywords: "security trust privacy" },
  lock: { label: "Lock", Icon: Lock, group: "Work & dev", keywords: "private secure" },
  key: { label: "Key", Icon: Key, group: "Work & dev", keywords: "access password login" },
  wifi: { label: "Wi-Fi", Icon: Wifi, group: "Work & dev", keywords: "internet network" },

  // Learning & content
  "book-open": { label: "Open book", Icon: BookOpen, group: "Learning & content", keywords: "read docs guide" },
  book: { label: "Book", Icon: Book, group: "Learning & content", keywords: "ebook read" },
  library: { label: "Library", Icon: Library, group: "Learning & content", keywords: "books resources" },
  "graduation-cap": { label: "Graduation", Icon: GraduationCap, group: "Learning & content", keywords: "course education university" },
  school: { label: "School", Icon: School, group: "Learning & content", keywords: "education academy" },
  lightbulb: { label: "Idea", Icon: Lightbulb, group: "Learning & content", keywords: "tips idea explain" },
  newspaper: { label: "News", Icon: Newspaper, group: "Learning & content", keywords: "blog article press" },
  "file-text": { label: "Document", Icon: FileText, group: "Learning & content", keywords: "article pdf cv resume" },
  "scroll-text": { label: "Scroll", Icon: ScrollText, group: "Learning & content", keywords: "terms story" },
  "notebook-pen": { label: "Notebook", Icon: NotebookPen, group: "Learning & content", keywords: "notes journal blog substack medium" },
  bookmark: { label: "Bookmark", Icon: Bookmark, group: "Learning & content", keywords: "save read later" },
  archive: { label: "Archive", Icon: Archive, group: "Learning & content", keywords: "history old" },
  folder: { label: "Folder", Icon: Folder, group: "Learning & content", keywords: "files drive" },
  download: { label: "Download", Icon: Download, group: "Learning & content", keywords: "file get" },
  upload: { label: "Upload", Icon: Upload, group: "Learning & content", keywords: "submit share" },

  // Money & shopping
  "shopping-bag": { label: "Shopping bag", Icon: ShoppingBag, group: "Money & shopping", keywords: "shop store merch" },
  "shopping-cart": { label: "Cart", Icon: ShoppingCart, group: "Money & shopping", keywords: "shop buy" },
  store: { label: "Store", Icon: Store, group: "Money & shopping", keywords: "shop market" },
  shirt: { label: "Merch", Icon: Shirt, group: "Money & shopping", keywords: "tshirt clothes fashion" },
  "credit-card": { label: "Credit card", Icon: CreditCard, group: "Money & shopping", keywords: "pay payment" },
  wallet: { label: "Wallet", Icon: Wallet, group: "Money & shopping", keywords: "money pay" },
  "dollar-sign": { label: "Dollar", Icon: DollarSign, group: "Money & shopping", keywords: "money price" },
  euro: { label: "Euro", Icon: Euro, group: "Money & shopping", keywords: "money price" },
  coins: { label: "Coins", Icon: Coins, group: "Money & shopping", keywords: "money crypto tip" },
  "piggy-bank": { label: "Savings", Icon: PiggyBank, group: "Money & shopping", keywords: "money finance" },
  receipt: { label: "Receipt", Icon: Receipt, group: "Money & shopping", keywords: "invoice bill" },
  tag: { label: "Tag", Icon: Tag, group: "Money & shopping", keywords: "price sale discount" },
  ticket: { label: "Ticket", Icon: Ticket, group: "Money & shopping", keywords: "event pass" },
  gift: { label: "Gift", Icon: Gift, group: "Money & shopping", keywords: "present giveaway" },
  coffee: { label: "Coffee", Icon: Coffee, group: "Money & shopping", keywords: "buy me a coffee ko-fi tip cafe" },
  calculator: { label: "Calculator", Icon: Calculator, group: "Money & shopping", keywords: "math tool" },
  landmark: { label: "Bank", Icon: Landmark, group: "Money & shopping", keywords: "finance government" },

  // Time & events
  timer: { label: "Timer", Icon: Timer, group: "Time & events", keywords: "pomodoro focus stopwatch" },
  clock: { label: "Clock", Icon: Clock, group: "Time & events", keywords: "time hours" },
  "alarm-clock": { label: "Alarm", Icon: AlarmClock, group: "Time & events", keywords: "reminder wake" },
  hourglass: { label: "Hourglass", Icon: Hourglass, group: "Time & events", keywords: "wait time" },
  calendar: { label: "Calendar", Icon: Calendar, group: "Time & events", keywords: "booking schedule calendly" },
  "calendar-days": { label: "Events", Icon: CalendarDays, group: "Time & events", keywords: "meetup schedule" },
  trophy: { label: "Trophy", Icon: Trophy, group: "Time & events", keywords: "award win competition" },
  award: { label: "Award", Icon: Award, group: "Time & events", keywords: "badge certificate" },
  medal: { label: "Medal", Icon: Medal, group: "Time & events", keywords: "achievement win" },
  crown: { label: "Crown", Icon: Crown, group: "Time & events", keywords: "premium vip king" },

  // Places & life
  globe: { label: "Globe", Icon: Globe, group: "Places & life", keywords: "website world web" },
  house: { label: "Home", Icon: House, group: "Places & life", keywords: "home house main" },
  "map-pin": { label: "Location", Icon: MapPin, group: "Places & life", keywords: "place address city" },
  map: { label: "Map", Icon: Map, group: "Places & life", keywords: "directions travel" },
  compass: { label: "Compass", Icon: Compass, group: "Places & life", keywords: "explore discover" },
  plane: { label: "Plane", Icon: Plane, group: "Places & life", keywords: "travel flight trip" },
  train: { label: "Train", Icon: TrainFront, group: "Places & life", keywords: "travel transit" },
  car: { label: "Car", Icon: Car, group: "Places & life", keywords: "drive travel" },
  bike: { label: "Bike", Icon: Bike, group: "Places & life", keywords: "cycling sport" },
  dumbbell: { label: "Fitness", Icon: Dumbbell, group: "Places & life", keywords: "gym sport health" },
  utensils: { label: "Food", Icon: Utensils, group: "Places & life", keywords: "restaurant recipe eat" },
  pizza: { label: "Pizza", Icon: Pizza, group: "Places & life", keywords: "food" },
  leaf: { label: "Leaf", Icon: Leaf, group: "Places & life", keywords: "nature eco green" },
  "tree-pine": { label: "Tree", Icon: TreePine, group: "Places & life", keywords: "nature outdoor forest" },
  mountain: { label: "Mountain", Icon: Mountain, group: "Places & life", keywords: "outdoor hiking adventure" },
  sun: { label: "Sun", Icon: Sun, group: "Places & life", keywords: "summer day light" },
  moon: { label: "Moon", Icon: Moon, group: "Places & life", keywords: "night dark" },
  "cloud-sun": { label: "Weather", Icon: CloudSun, group: "Places & life", keywords: "forecast" },

  // General
  link: { label: "Link", Icon: Link2, group: "General", keywords: "url chain website" },
  chain: { label: "Chain link", Icon: Link, group: "General", keywords: "url" },
  "external-link": { label: "External link", Icon: ExternalLink, group: "General", keywords: "open url" },
  share: { label: "Share", Icon: Share2, group: "General", keywords: "social" },
  "qr-code": { label: "QR code", Icon: QrCode, group: "General", keywords: "scan" },
  star: { label: "Star", Icon: Star, group: "General", keywords: "favorite rate review" },
  "thumbs-up": { label: "Thumbs up", Icon: ThumbsUp, group: "General", keywords: "like approve" },
  flame: { label: "Flame", Icon: Flame, group: "General", keywords: "hot fire trending" },
  zap: { label: "Zap", Icon: Zap, group: "General", keywords: "fast lightning energy" },
  pin: { label: "Pin", Icon: Pin, group: "General", keywords: "pinned important" },
  flag: { label: "Flag", Icon: Flag, group: "General", keywords: "report country" },
  search: { label: "Search", Icon: Search, group: "General", keywords: "find" },
  eye: { label: "Eye", Icon: Eye, group: "General", keywords: "view watch see" },
  info: { label: "Info", Icon: Info, group: "General", keywords: "about information" },
  help: { label: "Help", Icon: CircleQuestionMark, group: "General", keywords: "faq question support" },
} satisfies Record<string, IconDef>;

export type LinkIcon = keyof typeof LINK_ICON_REGISTRY;

export const LINK_ICONS = Object.keys(LINK_ICON_REGISTRY) as LinkIcon[];
